Fix: remove --ffi argument from bin/php/run

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -44,6 +44,9 @@ if [ "$MODE" == "test" ]; then
   ./bin/go/run $CLEAN --test "$TEST_NAME" || echo "=== Go failed ==="
   
   echo ""
+  ./bin/cs/run $CLEAN --test "$TEST_NAME" || echo "=== C# failed ==="
+  
+  echo ""
   ./bin/scm/run $CLEAN --test "$TEST_NAME" || echo "=== Scheme failed ==="
   
   echo ""
@@ -64,6 +67,9 @@ elif [ "$MODE" == "x" ]; then
   
   echo ""
   ./bin/go/run $CLEAN --x || echo "=== Go failed ==="
+  
+  echo ""
+  ./bin/cs/run $CLEAN --x || echo "=== C# failed ==="
 else
   echo "================================"
   echo "    Running pure backends...    "
@@ -85,4 +91,7 @@ else
   
   echo ""
   ./bin/go/run $CLEAN || echo "=== Go failed ==="
+  
+  echo ""
+  ./bin/cs/run $CLEAN || echo "=== C# failed ==="
 fi
