misc

diff --git a/bin/go/run b/bin/go/run
--- a/bin/go/run
+++ b/bin/go/run
@@ -77,7 +77,7 @@ echo 'Building...'
 spago build
 
 # Generate Go code
-node ../gopurs/gopurs/bin/gopurs.js --main ${ENTRY_POINT} || echo "GOPURS FAILED" || exit 1
+NODE_OPTIONS="--max-old-space-size=8192" node ../gopurs/gopurs/bin/gopurs.js --main ${ENTRY_POINT} || echo "GOPURS FAILED" || exit 1
 
 echo "=== Go ==="
 if [ -d "output/main" ]; then
