misc

diff --git a/bin/go/run b/bin/go/run
--- a/bin/go/run
+++ b/bin/go/run
@@ -88,7 +88,7 @@ echo 'Building...'
 spago build
 
 # Generate Go code
-NODE_OPTIONS="--max-old-space-size=8192" node --stack-size=65536 ../gopurs/gopurs/bin/gopurs.js --main ${ENTRY_POINT} || echo "GOPURS FAILED" || exit 1
+../gopurs/gopurs/bin/gopurs --main ${ENTRY_POINT} || echo "GOPURS FAILED" || exit 1
 
 echo "=== Go ==="
 if [ -d "output/main" ]; then
diff --git a/bin/java/run b/bin/java/run
--- a/bin/java/run
+++ b/bin/java/run
@@ -71,7 +71,7 @@ echo 'Building...'
 spago build
 
 # Generate Java code
-node ../javapurs/javapurs/bin/javapurs.js --main ${ENTRY_POINT} || { echo "JAVAPURS FAILED"; exit 1; }
+../javapurs/javapurs/bin/javapurs --main ${ENTRY_POINT} || { echo "JAVAPURS FAILED"; exit 1; }
 
 echo "=== Java ==="
 if [ -d "java_output" ] && [ -f "java_output/MainRun.java" ]; then
